apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    name: node
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node
  template:
    metadata:
      labels:
        name: node
    spec:
      containers:
        - name: node
          image: junereycasuga/node-demo:1.5
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
